// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"database/sql"
	audit2 "k8s-manager/market/internal/application/audit"
	plugin2 "k8s-manager/market/internal/application/plugin"
	user2 "k8s-manager/market/internal/application/user"
	"k8s-manager/market/internal/infrastructure/repository/artifact"
	"k8s-manager/market/internal/infrastructure/repository/audit"
	"k8s-manager/market/internal/infrastructure/repository/installation"
	"k8s-manager/market/internal/infrastructure/repository/plugin"
	"k8s-manager/market/internal/infrastructure/repository/publisher"
	"k8s-manager/market/internal/infrastructure/repository/release"
	"k8s-manager/market/internal/infrastructure/repository/user"
	"k8s-manager/market/internal/infrastructure/storage"
	"k8s-manager/market/internal/presentation/grpc"
	plugin3 "k8s-manager/market/internal/presentation/grpc/plugin"
	user3 "k8s-manager/market/internal/presentation/grpc/user"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp(db *sql.DB, grpcPort int, metricsPort MetricsPort, storagePath string) (*App, error) {
	postgresRepository := user.NewPostgresRepository(db)
	service := user2.NewService(postgresRepository)
	handler := user3.NewHandler(service)
	postgresPluginRepository := plugin.NewPostgresPluginRepository(db)
	postgresReleaseRepository := release.NewPostgresReleaseRepository(db)
	postgresArtifactRepository := artifact.NewPostgresArtifactRepository(db)
	postgresInstallationRepository := installation.NewPostgresInstallationRepository(db)
	postgresPublisherRepository := publisher.NewPostgresPublisherRepository(db)
	postgresAuditRepository := audit.NewPostgresAuditRepository(db)
	auditService := audit2.NewService(postgresAuditRepository)
	pluginService := plugin2.NewService(postgresPluginRepository, postgresReleaseRepository, postgresArtifactRepository, postgresInstallationRepository, postgresPublisherRepository, auditService)
	artifactStorage, err := storage.NewArtifactStorage(storagePath)
	if err != nil {
		return nil, err
	}
	pluginHandler := plugin3.NewHandler(pluginService, artifactStorage)
	server := grpc.NewServer(grpcPort, handler, pluginHandler)
	app := NewApp(server, metricsPort)
	return app, nil
}
