// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"database/sql"
	audit2 "k8s-manager/market/internal/application/audit"
	plugin2 "k8s-manager/market/internal/application/plugin"
	user2 "k8s-manager/market/internal/application/user"
	"k8s-manager/market/internal/infrastructure/repository/artifact"
	"k8s-manager/market/internal/infrastructure/repository/audit"
	"k8s-manager/market/internal/infrastructure/repository/plugin"
	"k8s-manager/market/internal/infrastructure/repository/publisher"
	"k8s-manager/market/internal/infrastructure/repository/release"
	"k8s-manager/market/internal/infrastructure/repository/user"
	"k8s-manager/market/internal/presentation/grpc"
	plugin3 "k8s-manager/market/internal/presentation/grpc/plugin"
	user3 "k8s-manager/market/internal/presentation/grpc/user"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp(db *sql.DB, grpcPort int, storagePath string) (*App, error) {
	postgresRepository := user.NewPostgresRepository(db)
	service := user2.NewService(postgresRepository)
	handler := user3.NewHandler(service)
	postgresPluginRepository := plugin.NewPostgresPluginRepository(db)
	postgresReleaseRepository := release.NewPostgresReleaseRepository(db)
	postgresArtifactRepository := artifact.NewPostgresArtifactRepository(db)
	postgresPublisherRepository := publisher.NewPostgresPublisherRepository(db)
	postgresAuditRepository := audit.NewPostgresAuditRepository(db)
	auditService := audit2.NewService(postgresAuditRepository)
	pluginService := plugin2.NewService(postgresPluginRepository, postgresReleaseRepository, postgresArtifactRepository, postgresPublisherRepository, auditService)
	pluginHandler := plugin3.NewHandler(pluginService)
	server := grpc.NewServer(grpcPort, handler, pluginHandler)
	app := NewApp(server)
	return app, nil
}
