# https://taskfile.dev

version: '3'

tasks:
  setup:
    desc: Install deps and tool for docs generation.
    cmds:
      - go mod download
  build:
    cmds:
      - go build -o bin/server ./cmd/cli
  test:
    cmds:
      - go test ./... -v
  clean:
    cmds:
      - rm -rf bin/
  get-test-token:
    cmds:
      - go run ./cmd/get-test-token
  test:
    cmds:
      - go run ./cmd/test
  default:
    cmds:
      - go run ./cmd/cli
