# https://taskfile.dev

version: '3'

tasks:
  setup:
    desc: Install deps and tool for docs generation.
    cmds:
      - go mod download
  build:
    cmds:
      - go build -o bin/k8s-manager ./cmd/cli
  test:
    cmds:
      - go test ./... -v
  clean:
    cmds:
      - rm -rf bin/
  default:
    cmds:
      - go run ./cmd/cli
