services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: k8s_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  market-service:
    build:
      context: ..
      dockerfile: market/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: k8s_market
      HTTP_PORT: 8080
      STORAGE_PATH: /app/storage
    volumes:
      - market_storage:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./market-service", "-db-host", "postgres", "-grpc-port", "8080", "-storage-path", "/app/storage"]

volumes:
  postgres_data:
  market_storage:

